# **NUMPY**

**What is Numpy?**

1.  NumPy is the library that gives Python its ability to work with data at speed. 

2. Numpy has several advantages over data cleaning and manipulation. 

3. It allows for efficient operations on the data structures often used in machine learning: vectors, matrices, and tensors.

4. It is a foundation package for scientific computing in python.

**Why Numpy?**

  1. Numpy ‘ndarray’ is a much more efficient way
of storing and manipulating “numerical data”
than the built-in Python data structures.

  2.  Libraries written in lower-level languages, such
as C, can operate on data stored in Numpy
‘ndarray’ without copying any data. 

  3.  It provides a high-performance multidimensional array
object, and tools for working with these arrays

# Numpy numerical types:

bool This stores boolean (True or False) as a bit

inti This is a platform integer (normally either int32 or int64)

int8 This is an integer ranging from-128 to 127

int16 This is an integer ranging from -32768 to 32767

int32 This is an integer ranging from -2 ** 31 to 2 ** 31 -1

int64 This is an integer ranging from -2 ** 63 to 2 ** 63 -1

uint8 This is an unsigned integer ranging from 0 to 255

uint16 This is an unsigned integer ranging from 0 to 65535

uint32 This is an unsigned integer ranging from 0 to 2 ** 32 - 1

uint64 This is an unsigned integer ranging from 0 to 2 ** 64 - 1

float16 This is a half precision float with sign bit, 5 bits exponent, and 10 bits mantissa

float32 This is a single precision float with sign bit, 8 bits exponent, and 23 bits mantissa

float64 or float This is a double precision float with sign bit, 11 bits exponent, and 52 bits mantissa

complex64 This is a complex number represented by two 32-bit floats (real and imaginary components)

complex128 or complex This is a complex number represented by two 64-bit floats (real and imaginary components)

# Numpy datatypes (dtypes)

integer
i

Unsigned integer
u

Single precision float
f

Double precision float
d

bool
b

complex
D

string
S

unicode
U

Void
V


# Import Convention

In [1]:
import numpy as np

# Creating Arrays with Numpy

In [2]:
# One dimensional array
np.array([1,2,3])

array([1, 2, 3])

In [3]:
# Two dimensional array
np.array([(1,2,3),(4,5,6)])

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
# 1D array of length 5 all values 0
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [5]:
# 3x3 array with all values 1
np.ones((4,4)) 

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [6]:
# 3x3 array of 0 with 1 on diagonal (Identity matrix)
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
# Array of 5 evenly divided values from 0 to 100
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [10]:
# Array of values from 0 to less than 10 with step 2
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [11]:
# 3x3 array with all values 7
np.full((3,3),7) 

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [12]:
# 4x4 array of random floats between 0–1
np.random.rand(4,4)

array([[0.07031811, 0.24283057, 0.06082343, 0.28774561],
       [0.45957183, 0.82631869, 0.68464435, 0.14801713],
       [0.47363432, 0.69825751, 0.34577729, 0.61328715],
       [0.40320951, 0.05118985, 0.09456923, 0.54965382]])

In [13]:
# 5x5 array of random floats between 0–50
np.random.rand(5,5)*50

array([[29.89800963, 30.17215764, 33.00371883,  5.95841849, 34.86850958],
       [18.12120953, 21.24048851,  6.52259681, 34.65740302, 44.30477751],
       [33.80439682, 11.93699376, 30.51366729, 37.00102272, 22.86154232],
       [ 6.42998321, 13.66414869, 25.36291656, 25.92720918, 49.90859785],
       [47.43902109, 17.31208148, 34.52771729, 21.67901847,  8.31993315]])

In [14]:
# 2x3 array with random integers between 0–4
np.random.randint(5,size=(2,3))

array([[3, 2, 2],
       [2, 4, 2]])

# Inspecting Properties with Numpy

In [15]:
a = np.random.rand(4,4)
print(a)

[[0.07438066 0.24705275 0.34217944 0.21139295]
 [0.69304319 0.30873375 0.8823934  0.51744141]
 [0.34061855 0.40251931 0.70368763 0.06763129]
 [0.82827395 0.25055308 0.82667082 0.31159826]]


In [16]:
# Returns number of elements in array
a.size

16

In [17]:
# Returns dimensions of array (rows,columns)
a.shape

(4, 4)

In [18]:
#  Returns type of elements in array
a.dtype

dtype('float64')

In [21]:
# Convert array elements to type dtype
a.astype("float32")

array([[0.07438066, 0.24705274, 0.34217945, 0.21139295],
       [0.6930432 , 0.30873376, 0.8823934 , 0.5174414 ],
       [0.34061855, 0.40251932, 0.7036876 , 0.06763129],
       [0.82827395, 0.25055307, 0.8266708 , 0.31159824]], dtype=float32)

In [22]:
# Convert array to a Python list
a.tolist()

[[0.07438066179858649,
  0.24705274846435643,
  0.34217944078914764,
  0.211392952066906],
 [0.6930431898868162,
  0.3087337522982101,
  0.88239339604661,
  0.5174414124768032],
 [0.3406185490336694,
  0.40251931085261616,
  0.7036876329532252,
  0.06763128608867508],
 [0.828273948814062,
  0.25055307565964546,
  0.8266708196364178,
  0.31159825538709585]]

# Copying, sorting, reshaping with Numpy

In [30]:
b = np.copy(a)
print(b)

[[0.07438066 0.24705275 0.34217944 0.21139295]
 [0.69304319 0.30873375 0.8823934  0.51744141]
 [0.34061855 0.40251931 0.70368763 0.06763129]
 [0.82827395 0.25055308 0.82667082 0.31159826]]


In [33]:
# Creates view of array elements with type dtype
b.view("float32")

array([[ 8.7127756e+27,  1.3987613e+00, -5.9192478e-14,  1.6220527e+00,
        -5.8778752e-24,  1.6710896e+00, -3.6681966e-22,  1.5863929e+00],
       [-1.7600494e+25,  1.7982607e+00,  3.1396648e-06,  1.6543669e+00,
         2.5148899e-27,  1.8455983e+00,  8.7743080e+06,  1.7543603e+00],
       [-1.5691140e-01,  1.6703092e+00,  3.8198529e+16,  1.7012596e+00,
        -3.7966100e+27,  1.8009218e+00, -6.9832744e-09,  1.3852625e+00],
       [ 3.6231563e+18,  1.8320684e+00, -9.9082007e+02,  1.6252764e+00,
         4.9690404e+17,  1.8316677e+00, -2.5536077e+09,  1.6557990e+00]],
      dtype=float32)

In [40]:
c = np.array([61,27,36,76,23])
print(c)

[61 27 36 76 23]


In [42]:
# Sorts array
sorted = np.sort(c)
print(sorted)

[23 27 36 61 76]


In [44]:
 # sort along the first axis
np.sort(c, axis=0) 

array([23, 27, 36, 61, 76])

In [48]:
# sort the flattened array
np.sort(a, axis=None)

array([0.06763129, 0.07438066, 0.21139295, 0.24705275, 0.25055308,
       0.30873375, 0.31159826, 0.34061855, 0.34217944, 0.40251931,
       0.51744141, 0.69304319, 0.70368763, 0.82667082, 0.82827395,
       0.8823934 ])

In [55]:
d = np.array([(1,2,3),(4,5,6)])
print(d)

[[1 2 3]
 [4 5 6]]


In [50]:
# Flattens 2D array to 1D
d.flatten()

array([1, 2, 3, 4, 5, 6])

In [53]:
# Transposes array (rows become columns and vice versa)
d.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [59]:
e = np.arange(6)
print(e)

[0 1 2 3 4 5]


In [61]:
# Reshapes array to 3 rows, 2 columns
e.reshape((3, 2))

array([[0, 1],
       [2, 3],
       [4, 5]])

In [63]:
# C-like index ordering
np.reshape(a, (2, 3)) 

array([[0, 1, 2],
       [3, 4, 5]])

In [64]:
# equivalent to C ravel then C reshape
# reshape and ravel are defined in numpy C code: PyArray_Ravel(PyArrayObject *arr, NPY_ORDER order)
np.reshape(np.ravel(a), (2, 3))

array([[0, 1, 2],
       [3, 4, 5]])

In [65]:
# Fortran-like index ordering
np.reshape(a, (2, 3), order='F')

array([[0, 2, 4],
       [1, 3, 5]])

In [66]:
# Changes array shape to 6: 1D 
np.reshape(a, 6)

array([0, 1, 2, 3, 4, 5])

In [79]:
# reshape array
data = np.zeros(50) 
out = data.reshape((2,5,5))
print(out)
print(out.size)
print(out.shape)    

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]
50
(2, 5, 5)


# Adding/removing Elements with Numpy

In [81]:
f = np.arange(0,10,2)
print(f)

[0 2 4 6 8]


In [82]:
# Appends values to end of array
np.append(f,"10")

array(['0', '2', '4', '6', '8', '10'], dtype='<U21')

In [84]:
# Inserts values into array before index 3
np.insert(f,3,5) 

array([0, 2, 4, 5, 6, 8])

In [87]:
# Deletes /data on index 3 of array
np.delete(f,3,axis=0) 

array([0, 2, 4, 8])

In [89]:
# Deletes column on index 2 of array
np.delete(b,2,axis=1) 

array([[0.07438066, 0.21139295, 0.34217944],
       [0.30873375, 0.51744141, 0.8823934 ],
       [0.06763129, 0.34061855, 0.70368763],
       [0.25055308, 0.31159826, 0.82827395]])

# Combining, splitting with Numpy

In [92]:
arr1 = np.arange(0,100,3)
arr2 = np.arange(0,100,10)
print(arr1)
print(arr2)

[ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69
 72 75 78 81 84 87 90 93 96 99]
[ 0 10 20 30 40 50 60 70 80 90]


In [93]:
# Adds arr2 as rows to the end of arr1
np.concatenate((arr1,arr2),axis=0)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99,
        0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [96]:
# Adds arr2 as columns to end of arr1
arr_c1 = np.full((3,3),7) 
arr_c2 = np.full((3,3),14) 
np.concatenate((arr_c1,arr_c2),axis=1)

array([[ 7,  7,  7, 14, 14, 14],
       [ 7,  7,  7, 14, 14, 14],
       [ 7,  7,  7, 14, 14, 14]])

In [98]:
# Splits arr into 2 sub-arrays
np.split(arr1,2)

[array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48]),
 array([51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])]

In [106]:
# Splits arr horizontally on the 5th index
np.hsplit(arr2,2) 

[array([ 0, 10, 20, 30, 40]), array([50, 60, 70, 80, 90])]

# Indexing,slicing,subsetting with Numpy

In [107]:
# Returns the element at index 5
arr1[5] 

15

In [114]:
# Returns the 2D array element on index [2][3]
b[2,3]

0.7036876329532252

In [116]:
# Assigns array element on index 1 the value 4
arr1[1]=4
print(arr1)

[ 0  4  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69
 72 75 78 81 84 87 90 93 96 99]


In [118]:
# Assigns array element on index [1][3] the value 10
arr_c1[1,2]=10
print(arr_c1)

[[ 7  7  7]
 [ 7  7 10]
 [ 7  7  7]]


In [120]:
# Returns the elements at indices 0,1,2
arr1[0:3]

array([0, 4, 6])

In [123]:
# On a 2D array: returns rows 0,1,2
arr_c2[0:3]

array([[14, 14, 14],
       [14, 14, 14],
       [14, 14, 14]])

In [124]:
#  Returns the elements on rows 0,1,2 at column 1
arr_c2[0:3,1]

array([14, 14, 14])

In [125]:
# Returns the elements at indices 0,1
arr2[:2]

array([ 0, 10])

In [126]:
# On a 2D array: returns rows 0,1
arr_c1[:2]

array([[ 7,  7,  7],
       [ 7,  7, 10]])

In [127]:
# Returns the elements at index 1 on all rows
arr_c1[:,1]

array([7, 7, 7])

In [129]:
# Returns an array with boolean values
arr_c1<10

array([[ True,  True,  True],
       [ True,  True, False],
       [ True,  True,  True]])

In [142]:
# Returns an array with boolean values
bo = arr_c1>7
print(bo)

[[False False False]
 [False False  True]
 [False False False]]


In [143]:
# Inverts a boolean array
~bo

array([[ True,  True,  True],
       [ True,  True, False],
       [ True,  True,  True]])

In [147]:
# Returns array elements greater than 7
arr_c1[arr_c1>7]

array([10])

# Scalar Math with Numpy

In [149]:
#  Add 1 to each array elementv
np.add(arr1,1)

array([  1,   5,   7,  10,  13,  16,  19,  22,  25,  28,  31,  34,  37,
        40,  43,  46,  49,  52,  55,  58,  61,  64,  67,  70,  73,  76,
        79,  82,  85,  88,  91,  94,  97, 100])

In [150]:
# Subtract 2 from each array element
np.subtract(arr2,2)

array([-2,  8, 18, 28, 38, 48, 58, 68, 78, 88])

In [151]:
# Multiply each array element by 3
np.multiply(arr2,3)

array([  0,  30,  60,  90, 120, 150, 180, 210, 240, 270])

In [152]:
#   Divide each array element by 4
np.divide(arr2,5)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18.])

In [153]:
# Raise each array element to the 5th power
np.power(arr2,5) 

array([         0,     100000,    3200000,   24300000,  102400000,
        312500000,  777600000, 1680700000, 3276800000, 5904900000])

# Vector Math with numpy

In [154]:
# Elementwise add array2 to array1
np.add(arr_c1,arr_c2)

array([[21, 21, 21],
       [21, 21, 24],
       [21, 21, 21]])

In [155]:
# Elementwise subtract array2 from array1
np.subtract(arr_c1,arr_c2)

array([[-7, -7, -7],
       [-7, -7, -4],
       [-7, -7, -7]])

In [156]:
# Elementwise multiply array1 by array2
np.multiply(arr_c1,arr_c1)

array([[ 49,  49,  49],
       [ 49,  49, 100],
       [ 49,  49,  49]])

In [157]:
# Elementwise divide array1 by array2
np.divide(arr_c1,arr_c2) 

array([[0.5       , 0.5       , 0.5       ],
       [0.5       , 0.5       , 0.71428571],
       [0.5       , 0.5       , 0.5       ]])

In [159]:
# Elementwise raise array1 raised to the power of array2
np.power(arr_c1,arr_c2)

array([[   678223072849,    678223072849,    678223072849],
       [   678223072849,    678223072849, 100000000000000],
       [   678223072849,    678223072849,    678223072849]])

In [160]:
# Returns True if the arrays have the same elements and shape
np.array_equal(arr_c1,arr_c2)

False

In [162]:
# Square root of each element in the array
np.sqrt(arr_c1)

array([[2.64575131, 2.64575131, 2.64575131],
       [2.64575131, 2.64575131, 3.16227766],
       [2.64575131, 2.64575131, 2.64575131]])

In [163]:
# Sine of each element in the array
np.sin(arr_c1)

array([[ 0.6569866 ,  0.6569866 ,  0.6569866 ],
       [ 0.6569866 ,  0.6569866 , -0.54402111],
       [ 0.6569866 ,  0.6569866 ,  0.6569866 ]])

In [164]:
# Natural log of each element in the array
np.log(arr_c1)

array([[1.94591015, 1.94591015, 1.94591015],
       [1.94591015, 1.94591015, 2.30258509],
       [1.94591015, 1.94591015, 1.94591015]])

In [165]:
# Absolute value of each element in the array
np.abs(arr_c1)

array([[ 7,  7,  7],
       [ 7,  7, 10],
       [ 7,  7,  7]])

In [166]:
# Rounds up to the nearest int
np.ceil(arr1)

array([ 0.,  4.,  6.,  9., 12., 15., 18., 21., 24., 27., 30., 33., 36.,
       39., 42., 45., 48., 51., 54., 57., 60., 63., 66., 69., 72., 75.,
       78., 81., 84., 87., 90., 93., 96., 99.])

In [167]:
# Rounds down to the nearest int
np.floor(arr1)

array([ 0.,  4.,  6.,  9., 12., 15., 18., 21., 24., 27., 30., 33., 36.,
       39., 42., 45., 48., 51., 54., 57., 60., 63., 66., 69., 72., 75.,
       78., 81., 84., 87., 90., 93., 96., 99.])

In [170]:
# Rounds to the nearest int
np.round(arr1)

array([ 0,  4,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

# Statistics with Numpy

In [171]:
# Returns mean along specific axis
np.mean(arr_c1,axis=0)

array([7., 7., 8.])

In [172]:
np.mean(arr_c1,axis=1)

array([7., 8., 7.])

In [173]:
# Returns sum of array
arr1.sum()

1684

In [174]:
# Returns minimum value of arr
arr1.min()

0

In [178]:
#  Returns maximum value
arr1.max()

99

In [179]:
#  Returns the variance of array
np.var(arr2)

825.0

In [181]:
# Returns the standard deviation of specific axis
np.std(arr_c2,axis=1)

array([0., 0., 0.])

In [186]:
#  Returns correlation coefficient of array
np.corrcoef(arr_c1)

/usr/local/lib/python3.6/dist-packages/numpy/lib/function_base.py:2534: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/usr/local/lib/python3.6/dist-packages/numpy/lib/function_base.py:2535: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]


array([[nan, nan, nan],
       [nan,  1., nan],
       [nan, nan, nan]])

In [224]:
# Cumulative sum of the elements
arr_c1.cumsum(axis=1)

array([[ 7, 14, 21],
       [ 7, 14, 24],
       [ 7, 14, 21]])

# Importing, exporting with Numpy

In [192]:
#  From a text file
np.loadtxt("file.txt", delimiter=",")

array([[ 1., 10.,  1., 11.,  1., 13.,  1., 12.,  1.,  1.,  9.],
       [ 2., 11.,  2., 13.,  2., 10.,  2., 12.,  2.,  1.,  9.],
       [ 3., 12.,  3., 11.,  3., 13.,  3., 10.,  3.,  1.,  9.]])

In [194]:
# From a CSV file
np.genfromtxt('file.csv')

array([[1., 1., 1., 1., 5., 3., 3., 3., 7.],
       [6., 7., 8., 2., 2., 8., 5., 3., 3.],
       [8., 8., 8., 8., 8., 8., 8., 3., 7.]])

In [195]:
# Writes to a text file
np.savetxt('file.txt',arr1,delimiter=' ')

In [196]:
# Writes to a CSV file
np.savetxt('file.csv',arr_c1,delimiter=',')

# Common Operations, Set Methods, Matrices with Numpy

In [197]:
arr_c1.transpose()

array([[ 7,  7,  7],
       [ 7,  7,  7],
       [ 7, 10,  7]])

In [198]:
arr_c1.swapaxes(0, 1)

array([[ 7,  7,  7],
       [ 7,  7,  7],
       [ 7, 10,  7]])

In [199]:
# Vectorized expressions np.where(cond, x, y)
np.where([True, False], [1, 2],[2, 3])

array([1, 3])

In [202]:
np.unique(arr_c1)

array([ 7, 10])

In [206]:
# Set methods:  Test membership of ndarray1 values in [2, 3, 6]
np.in1d(arr_c1, [2,7,6]) 

array([ True,  True,  True,  True,  True, False,  True,  True,  True])

In [205]:
np.intersect1d(arr_c1, [2,7,6])

array([7])

In [208]:
np.union1d(arr_c1, arr_c2)

array([ 7, 10, 14])

In [209]:
np.setdiff1d(arr_c1, arr_c2)

array([ 7, 10])

In [210]:
np.setxor1d(arr_c1, arr_c2)

array([ 7, 10, 14])

In [ ]:
np1 = np.array([1,2,3,4,5])

In [ ]:
np1

array([1, 2, 3, 4, 5])

In [ ]:
type(np1)

numpy.ndarray

In [ ]:
Mat1 = np.array([[1,2],[3,4]])

In [ ]:
Mat1

array([[1, 2],
       [3, 4]])

In [ ]:
np1.shape

(5,)

In [ ]:
Mat1.shape

(2, 2)

In [ ]:
Mat1.dtype

dtype('int64')

In [ ]:
Mat1[0,0]  =  5

In [ ]:
Mat1

array([[5, 2],
       [3, 4]])

In [ ]:
Mat2 = np.arange(0,10,1)

In [ ]:
Mat2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
Mat3 = np.linspace(0,10,20)

In [ ]:
Mat3

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [ ]:
Mat3.shape

(20,)

In [ ]:
Mat4 = np.random.randn(5,5)

In [ ]:
Mat4

array([[ 1.50613655, -0.33245083,  0.53828072, -0.06749832, -0.32583383],
       [-0.55236893,  1.58451526, -0.26685426, -0.36966032, -0.83171971],
       [ 1.45780458, -0.33479644,  1.26040738,  0.98278778, -0.1120757 ],
       [ 1.27918792,  2.04879061,  0.16990297, -2.53093434, -0.16669399],
       [-0.21930765,  0.35495216, -0.18800691,  0.69455597, -0.30413106]])

In [ ]:
Mat5 = np.random.rand(5,5)

In [ ]:
Mat5

array([[7.01649331e-01, 2.44689941e-01, 8.42695767e-01, 1.35464204e-02,
        9.40781358e-01],
       [7.75650701e-01, 7.47374614e-02, 6.57916148e-01, 7.54681524e-01,
        2.25107170e-01],
       [7.35868538e-01, 7.98789621e-01, 8.89404995e-01, 4.50035604e-02,
        4.27830094e-01],
       [2.86701853e-01, 4.03571886e-01, 5.46858578e-04, 5.20255838e-01,
        3.81647609e-01],
       [5.11606285e-01, 2.54725187e-01, 6.50969882e-01, 3.81034371e-01,
        4.61154272e-01]])

In [ ]:
Mat5[0,1]

0.24468994132379196

In [ ]:
Mat5[0:3]

array([[0.70164933, 0.24468994, 0.84269577, 0.01354642, 0.94078136],
       [0.7756507 , 0.07473746, 0.65791615, 0.75468152, 0.22510717],
       [0.73586854, 0.79878962, 0.889405  , 0.04500356, 0.42783009]])

In [ ]:
Mat5[0:3, :]

array([[0.70164933, 0.24468994, 0.84269577, 0.01354642, 0.94078136],
       [0.7756507 , 0.07473746, 0.65791615, 0.75468152, 0.22510717],
       [0.73586854, 0.79878962, 0.889405  , 0.04500356, 0.42783009]])

In [212]:
#  sum of all the diagonal elements of a square matrix.
arr = np.array([[2, 0, 0], [0, 2, 0], [0, 0, 2]])
np.trace(arr)

6

In [213]:
# determinant of matrix
matrix = np.array([[1, 2, 3],
                   [2, 4, 6],
                   [3, 8, 9]])
np.linalg.det(matrix)

0.0

In [216]:
# matrix rank
matrix = np.array([[1, 1, 3],
                   [1, 2, 4],
                   [1, 3, 0]])
np.linalg.matrix_rank(matrix)

3

In [218]:
# Calculate eigenvalues and eigenvectors
matrix = np.array([[0, 1, 2],
                   [3, 4, 5],
                   [6, 7, 8]])

eigenvalues, eigenvectors = np.linalg.eig(matrix)

print(eigenvalues)
print(eigenvectors)

[ 1.33484692e+01 -1.34846923e+00 -2.48477279e-16]
[[ 0.16476382  0.79969966  0.40824829]
 [ 0.50577448  0.10420579 -0.81649658]
 [ 0.84678513 -0.59128809  0.40824829]]


In [219]:
eigenvalues1, eigenvectors1 = np.linalg.eig(arr_c1)
print(eigenvalues1)
print(eigenvectors1)

[ 2.19564392e+01  1.10590230e-15 -9.56439237e-01]
[[-5.51155602e-01 -7.07106781e-01  3.90279585e-01]
 [-6.26462294e-01  7.07106781e-01 -8.33884699e-01]
 [-5.51155602e-01 -6.58259668e-17  3.90279585e-01]]


In [220]:
# append values to the end of a given array.
np.append ([0, 1, 2], [[3, 4, 5], [6, 7, 8]])

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [221]:
np.append([[0, 1, 2], [3, 4, 5]],[[6, 7, 8]], axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])